using AtermisShop.Application.Common.Interfaces;
using AtermisShop.Domain.Chat;
using AtermisShop.Domain.News;
using AtermisShop.Domain.Orders;
using AtermisShop.Domain.Products;
using AtermisShop.Domain.Users;
using AtermisShop.Domain.Wishlist;
using Microsoft.EntityFrameworkCore;

namespace AtermisShop.Infrastructure.Persistence;

public class ApplicationDbContext : DbContext, IApplicationDbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);

        // Configure Users table
        builder.Entity<ApplicationUser>(entity =>
        {
            entity.ToTable("Users");
            entity.HasKey(e => e.Id);
            
            entity.Property(e => e.Id).IsRequired();
            entity.Property(e => e.Email).IsRequired().HasMaxLength(256);
            entity.Property(e => e.PasswordHash).IsRequired();
            entity.Property(e => e.FullName).IsRequired();
            entity.Property(e => e.PhoneNumber).HasMaxLength(50);
            entity.Property(e => e.Role).IsRequired();
            entity.Property(e => e.IsActive).IsRequired().HasDefaultValue(true);
            // EmailVerified must be explicitly set in code, not generated by database
            // Use ValueGeneratedNever() to ensure EF Core always includes this column in INSERT statements
            entity.Property(e => e.EmailVerified)
                .IsRequired()
                .HasDefaultValue(false)
                .ValueGeneratedNever();
            entity.Property(e => e.CreatedAt).IsRequired().HasDefaultValueSql("NOW()");
            entity.Property(e => e.UpdatedAt).IsRequired().HasDefaultValueSql("NOW()");
            
            entity.HasIndex(e => e.Email).IsUnique();
        });

        // Đổi tên các bảng theo schema mới
        builder.Entity<ProductCategory>().ToTable("ProductCategories");
        builder.Entity<NewsPost>().ToTable("NewsPosts");
        builder.Entity<Wishlist>().ToTable("Wishlists");
    }

    // Products
    public DbSet<Product> Products => Set<Product>();
    public DbSet<ProductCategory> ProductCategories => Set<ProductCategory>();
    public DbSet<ProductVariant> ProductVariants => Set<ProductVariant>();
    public DbSet<ProductImage> ProductImages => Set<ProductImage>();
    public DbSet<ProductSpecification> ProductSpecifications => Set<ProductSpecification>();
    public DbSet<ProductReview> ProductReviews => Set<ProductReview>();
    public DbSet<ProductComment> ProductComments => Set<ProductComment>();
    public DbSet<InventoryTransaction> InventoryTransactions => Set<InventoryTransaction>();

    // Orders
    public DbSet<Cart> Carts => Set<Cart>();
    public DbSet<CartItem> CartItems => Set<CartItem>();
    public DbSet<Order> Orders => Set<Order>();
    public DbSet<OrderItem> OrderItems => Set<OrderItem>();
    public DbSet<Voucher> Vouchers => Set<Voucher>();
    public DbSet<VoucherUsage> VoucherUsages => Set<VoucherUsage>();
    public DbSet<Payment> Payments => Set<Payment>();

    // News
    public DbSet<NewsPost> NewsPosts => Set<NewsPost>();

    // Wishlist
    public DbSet<Wishlist> Wishlists => Set<Wishlist>();

    // Users
    public DbSet<ApplicationUser> Users => Set<ApplicationUser>();
    public DbSet<RefreshToken> RefreshTokens => Set<RefreshToken>();
    public DbSet<EmailVerificationToken> EmailVerificationTokens => Set<EmailVerificationToken>();
    public DbSet<PasswordResetToken> PasswordResetTokens => Set<PasswordResetToken>();

    // Chat
    public DbSet<ChatMessage> ChatMessages => Set<ChatMessage>();

    public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        // Set UpdatedAt khi có thay đổi
        var entries = ChangeTracker.Entries<ApplicationUser>()
            .Where(e => e.State == EntityState.Added || e.State == EntityState.Modified);

        foreach (var entry in entries)
        {
            var user = entry.Entity;
            
            if (entry.State == EntityState.Modified)
            {
                user.UpdatedAt = DateTime.UtcNow;
            }
            else if (entry.State == EntityState.Added)
            {
                if (user.CreatedAt == default)
                    user.CreatedAt = DateTime.UtcNow;
                if (user.UpdatedAt == default)
                    user.UpdatedAt = DateTime.UtcNow;
                // Ensure boolean fields have default values to avoid null constraint violations
                // Note: These should already be set in UserService, but setting here as a safety measure
                if (!user.IsActive)
                    user.IsActive = true;
                // Explicitly set EmailVerified to false to ensure it's always included in INSERT
                // This prevents NULL constraint violation
                user.EmailVerified = false;
                // Mark the property as modified to ensure EF Core includes it in INSERT
                entry.Property(e => e.EmailVerified).IsModified = true;
            }
        }

        return await base.SaveChangesAsync(cancellationToken);
    }

    Task<int> IApplicationDbContext.SaveChangesAsync(CancellationToken cancellationToken)
    {
        return SaveChangesAsync(cancellationToken);
    }
}


