CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "ProductCategories" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "Description" text,
        "ParentId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ProductCategories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductCategories_ProductCategories_ParentId" FOREIGN KEY ("ParentId") REFERENCES "ProductCategories" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "Roles" (
        "Id" uuid NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "Users" (
        "Id" uuid NOT NULL,
        "FullName" text,
        "GoogleId" text,
        "Avatar" text,
        "EmailVerified" boolean NOT NULL,
        "Role" integer NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "Vouchers" (
        "Id" uuid NOT NULL,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "Description" text NOT NULL,
        "DiscountType" integer NOT NULL,
        "DiscountValue" numeric NOT NULL,
        "MaxDiscountAmount" numeric,
        "MinOrderAmount" numeric,
        "StartDate" timestamp with time zone NOT NULL,
        "EndDate" timestamp with time zone NOT NULL,
        "IsPublic" boolean NOT NULL,
        "UsageLimitTotal" integer NOT NULL,
        "UsageLimitPerCustomer" integer NOT NULL,
        "UsedCount" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Vouchers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "Products" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "Slug" text NOT NULL,
        "Description" text,
        "Price" numeric NOT NULL,
        "OriginalPrice" numeric NOT NULL,
        "StockQuantity" integer NOT NULL,
        "Brand" text,
        "IsActive" boolean NOT NULL,
        "HasVariants" boolean NOT NULL,
        "CategoryId" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Products_ProductCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "ProductCategories" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "RoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "Carts" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Carts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Carts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "ChatMessages" (
        "Id" uuid NOT NULL,
        "UserId" uuid,
        "Message" text NOT NULL,
        "SessionId" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ChatMessages_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "EmailVerificationTokens" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Token" text NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsUsed" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_EmailVerificationTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EmailVerificationTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "NewsPosts" (
        "Id" uuid NOT NULL,
        "Title" text NOT NULL,
        "Slug" text NOT NULL,
        "Content" text NOT NULL,
        "Summary" text,
        "ThumbnailUrl" text,
        "AuthorId" uuid,
        "Category" text,
        "Tags" text,
        "IsPublished" boolean NOT NULL,
        "PublishedAt" timestamp with time zone,
        "ViewCount" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_NewsPosts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_NewsPosts_Users_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "Users" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "RefreshTokens" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Token" text NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "RevokedAt" timestamp with time zone,
        "IpAddress" text,
        "UserAgent" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "UserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "UserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "UserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "UserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "Orders" (
        "Id" uuid NOT NULL,
        "OrderNumber" uuid NOT NULL,
        "UserId" uuid,
        "GuestEmail" text,
        "GuestFullName" text,
        "TotalAmount" numeric NOT NULL,
        "PaymentStatus" integer NOT NULL,
        "OrderStatus" integer NOT NULL,
        "PaymentMethod" integer NOT NULL,
        "PaymentTransactionId" text,
        "ShippingFullName" text,
        "ShippingPhoneNumber" text,
        "ShippingAddressLine" text,
        "ShippingWard" text,
        "ShippingDistrict" text,
        "ShippingCity" text,
        "VoucherId" uuid,
        "VoucherDiscountAmount" numeric,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Orders_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id"),
        CONSTRAINT "FK_Orders_Vouchers_VoucherId" FOREIGN KEY ("VoucherId") REFERENCES "Vouchers" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "InventoryTransactions" (
        "Id" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "ChangeQuantity" integer NOT NULL,
        "Reason" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_InventoryTransactions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_InventoryTransactions_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "ProductComments" (
        "Id" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "ParentCommentId" uuid,
        "Content" text NOT NULL,
        "IsEdited" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ProductComments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductComments_ProductComments_ParentCommentId" FOREIGN KEY ("ParentCommentId") REFERENCES "ProductComments" ("Id"),
        CONSTRAINT "FK_ProductComments_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ProductComments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "ProductImages" (
        "Id" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "ImageUrl" text NOT NULL,
        "IsPrimary" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ProductImages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductImages_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "ProductReviews" (
        "Id" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "UserId" uuid,
        "Rating" integer NOT NULL,
        "Comment" text NOT NULL,
        "FullName" text,
        "PhoneNumber" text,
        "Email" text,
        "ReviewImageUrl" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ProductReviews" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductReviews_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ProductReviews_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "ProductSpecifications" (
        "Id" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "Key" text NOT NULL,
        "Value" text NOT NULL,
        "DisplayOrder" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ProductSpecifications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductSpecifications_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "ProductVariants" (
        "Id" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "Color" text,
        "Size" text,
        "Spec" text,
        "Price" numeric NOT NULL,
        "OriginalPrice" numeric NOT NULL,
        "StockQuantity" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ProductVariants" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductVariants_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "Wishlists" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Wishlists" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Wishlists_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Wishlists_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "Payments" (
        "Id" uuid NOT NULL,
        "OrderId" uuid NOT NULL,
        "PaymentGateway" integer NOT NULL,
        "Amount" numeric NOT NULL,
        "Currency" text NOT NULL,
        "TransactionId" text,
        "Status" integer NOT NULL,
        "RawResponse" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Payments_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "VoucherUsages" (
        "Id" uuid NOT NULL,
        "VoucherId" uuid NOT NULL,
        "OrderId" uuid,
        "UserId" uuid,
        "GuestEmail" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_VoucherUsages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VoucherUsages_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id"),
        CONSTRAINT "FK_VoucherUsages_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id"),
        CONSTRAINT "FK_VoucherUsages_Vouchers_VoucherId" FOREIGN KEY ("VoucherId") REFERENCES "Vouchers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "CartItems" (
        "Id" uuid NOT NULL,
        "CartId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "ProductVariantId" uuid,
        "Quantity" integer NOT NULL,
        "UnitPriceSnapshot" numeric NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_CartItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CartItems_Carts_CartId" FOREIGN KEY ("CartId") REFERENCES "Carts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CartItems_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("Id"),
        CONSTRAINT "FK_CartItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE TABLE "OrderItems" (
        "Id" uuid NOT NULL,
        "OrderId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "ProductVariantId" uuid,
        "ProductNameSnapshot" text NOT NULL,
        "VariantInfoSnapshot" text,
        "Quantity" integer NOT NULL,
        "UnitPrice" numeric NOT NULL,
        "LineTotal" numeric NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_OrderItems_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("Id"),
        CONSTRAINT "FK_OrderItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_CartItems_CartId" ON "CartItems" ("CartId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_CartItems_ProductId" ON "CartItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_CartItems_ProductVariantId" ON "CartItems" ("ProductVariantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_Carts_UserId" ON "Carts" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_ChatMessages_UserId" ON "ChatMessages" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_EmailVerificationTokens_UserId" ON "EmailVerificationTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_InventoryTransactions_ProductId" ON "InventoryTransactions" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_NewsPosts_AuthorId" ON "NewsPosts" ("AuthorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_OrderItems_ProductId" ON "OrderItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_OrderItems_ProductVariantId" ON "OrderItems" ("ProductVariantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_Orders_UserId" ON "Orders" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_Orders_VoucherId" ON "Orders" ("VoucherId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_Payments_OrderId" ON "Payments" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_ProductCategories_ParentId" ON "ProductCategories" ("ParentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_ProductComments_ParentCommentId" ON "ProductComments" ("ParentCommentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_ProductComments_ProductId" ON "ProductComments" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_ProductComments_UserId" ON "ProductComments" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_ProductImages_ProductId" ON "ProductImages" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_ProductReviews_ProductId" ON "ProductReviews" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_ProductReviews_UserId" ON "ProductReviews" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_ProductSpecifications_ProductId" ON "ProductSpecifications" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_ProductVariants_ProductId" ON "ProductVariants" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_RoleClaims_RoleId" ON "RoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "Roles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_UserClaims_UserId" ON "UserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_UserLogins_UserId" ON "UserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "EmailIndex" ON "Users" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "Users" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_VoucherUsages_OrderId" ON "VoucherUsages" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_VoucherUsages_UserId" ON "VoucherUsages" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_VoucherUsages_VoucherId" ON "VoucherUsages" ("VoucherId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_Wishlists_ProductId" ON "Wishlists" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    CREATE INDEX "IX_Wishlists_UserId" ON "Wishlists" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133700_InitialSchemaWithNewDesign') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251222133700_InitialSchemaWithNewDesign', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222140000_AddUserFieldsIsActiveCreatedAtUpdatedAt') THEN
    ALTER TABLE "Users" ADD "IsActive" boolean NOT NULL DEFAULT TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222140000_AddUserFieldsIsActiveCreatedAtUpdatedAt') THEN
    ALTER TABLE "Users" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW());
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222140000_AddUserFieldsIsActiveCreatedAtUpdatedAt') THEN
    ALTER TABLE "Users" ADD "UpdatedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222140000_AddUserFieldsIsActiveCreatedAtUpdatedAt') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251222140000_AddUserFieldsIsActiveCreatedAtUpdatedAt', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251223160510_RemoveIdentityTablesAndUpdateUsers') THEN

                    DO $$ 
                    BEGIN
                        -- Drop foreign keys from UserRoles if exists
                        IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_UserRoles_Users_UserId' AND table_name = 'UserRoles') THEN
                            ALTER TABLE "UserRoles" DROP CONSTRAINT "FK_UserRoles_Users_UserId";
                        END IF;
                        IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_UserRoles_Roles_RoleId' AND table_name = 'UserRoles') THEN
                            ALTER TABLE "UserRoles" DROP CONSTRAINT "FK_UserRoles_Roles_RoleId";
                        END IF;
                        
                        -- Drop foreign keys from UserClaims if exists
                        IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_UserClaims_Users_UserId' AND table_name = 'UserClaims') THEN
                            ALTER TABLE "UserClaims" DROP CONSTRAINT "FK_UserClaims_Users_UserId";
                        END IF;
                        
                        -- Drop foreign keys from UserLogins if exists
                        IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_UserLogins_Users_UserId' AND table_name = 'UserLogins') THEN
                            ALTER TABLE "UserLogins" DROP CONSTRAINT "FK_UserLogins_Users_UserId";
                        END IF;
                        
                        -- Drop foreign keys from UserTokens if exists
                        IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_UserTokens_Users_UserId' AND table_name = 'UserTokens') THEN
                            ALTER TABLE "UserTokens" DROP CONSTRAINT "FK_UserTokens_Users_UserId";
                        END IF;
                        
                        -- Drop foreign keys from RoleClaims if exists
                        IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'FK_RoleClaims_Roles_RoleId' AND table_name = 'RoleClaims') THEN
                            ALTER TABLE "RoleClaims" DROP CONSTRAINT "FK_RoleClaims_Roles_RoleId";
                        END IF;
                    END $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251223160510_RemoveIdentityTablesAndUpdateUsers') THEN

                    DROP TABLE IF EXISTS "UserRoles" CASCADE;
                    DROP TABLE IF EXISTS "UserClaims" CASCADE;
                    DROP TABLE IF EXISTS "UserLogins" CASCADE;
                    DROP TABLE IF EXISTS "UserTokens" CASCADE;
                    DROP TABLE IF EXISTS "RoleClaims" CASCADE;
                    DROP TABLE IF EXISTS "Roles" CASCADE;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251223160510_RemoveIdentityTablesAndUpdateUsers') THEN

                    -- Remove Identity-related columns if they exist
                    ALTER TABLE "Users" 
                    DROP COLUMN IF EXISTS "UserName",
                    DROP COLUMN IF EXISTS "NormalizedUserName",
                    DROP COLUMN IF EXISTS "NormalizedEmail",
                    DROP COLUMN IF EXISTS "EmailConfirmed",
                    DROP COLUMN IF EXISTS "SecurityStamp",
                    DROP COLUMN IF EXISTS "ConcurrencyStamp",
                    DROP COLUMN IF EXISTS "PhoneNumberConfirmed",
                    DROP COLUMN IF EXISTS "TwoFactorEnabled",
                    DROP COLUMN IF EXISTS "LockoutEnd",
                    DROP COLUMN IF EXISTS "LockoutEnabled",
                    DROP COLUMN IF EXISTS "AccessFailedCount";
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251223160510_RemoveIdentityTablesAndUpdateUsers') THEN

                    -- Update existing NULL values BEFORE setting NOT NULL constraints
                    UPDATE "Users" 
                    SET 
                        "PasswordHash" = COALESCE("PasswordHash", ''),
                        "FullName" = COALESCE("FullName", COALESCE("Email", 'User')),
                        "Role" = COALESCE("Role", 0),
                        "IsActive" = COALESCE("IsActive", true),
                        "EmailVerified" = COALESCE("EmailVerified", false),
                        "CreatedAt" = COALESCE("CreatedAt", NOW()),
                        "UpdatedAt" = COALESCE("UpdatedAt", NOW())
                    WHERE "PasswordHash" IS NULL OR "FullName" IS NULL OR "PasswordHash" = '' OR "FullName" = '' OR "Email" IS NULL;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251223160510_RemoveIdentityTablesAndUpdateUsers') THEN

                    -- Set NOT NULL constraints after updating NULL values
                    ALTER TABLE "Users"
                    ALTER COLUMN "Email" SET NOT NULL,
                    ALTER COLUMN "PasswordHash" SET NOT NULL,
                    ALTER COLUMN "FullName" SET NOT NULL;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251223160510_RemoveIdentityTablesAndUpdateUsers') THEN

                    CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251223160510_RemoveIdentityTablesAndUpdateUsers') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251223160510_RemoveIdentityTablesAndUpdateUsers', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226081536_ChangeOrderNumberToString') THEN
    ALTER TABLE "Orders" ADD "OrderNumberNew" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226081536_ChangeOrderNumberToString') THEN

                    DO $$
                    DECLARE
                        order_record RECORD;
                        new_order_number TEXT;
                        counter INT := 0;
                    BEGIN
                        FOR order_record IN SELECT "Id" FROM "Orders" ORDER BY "CreatedAt"
                        LOOP
                            -- Generate a unique 7-digit number (1000000 to 9999999)
                            LOOP
                                new_order_number := LPAD((FLOOR(RANDOM() * 9000000)::INT + 1000000)::TEXT, 7, '0');
                                EXIT WHEN NOT EXISTS (SELECT 1 FROM "Orders" WHERE "OrderNumberNew" = new_order_number);
                            END LOOP;
                            
                            UPDATE "Orders"
                            SET "OrderNumberNew" = new_order_number
                            WHERE "Id" = order_record."Id";
                            
                            counter := counter + 1;
                        END LOOP;
                    END $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226081536_ChangeOrderNumberToString') THEN
    ALTER TABLE "Orders" DROP COLUMN "OrderNumber";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226081536_ChangeOrderNumberToString') THEN
    ALTER TABLE "Orders" RENAME COLUMN "OrderNumberNew" TO "OrderNumber";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251226081536_ChangeOrderNumberToString') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251226081536_ChangeOrderNumberToString', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251228150817_FixEmailVerifiedNullConstraint') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251228150817_FixEmailVerifiedNullConstraint', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230153958_MakeOriginalPriceNullable') THEN
    ALTER TABLE "ProductVariants" ALTER COLUMN "OriginalPrice" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230153958_MakeOriginalPriceNullable') THEN
    ALTER TABLE "Products" ALTER COLUMN "OriginalPrice" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230153958_MakeOriginalPriceNullable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251230153958_MakeOriginalPriceNullable', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230173614_AddEngravingTextToCartItemAndOrderItem') THEN
    ALTER TABLE "OrderItems" ADD "EngravingText" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230173614_AddEngravingTextToCartItemAndOrderItem') THEN
    ALTER TABLE "CartItems" ADD "EngravingText" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230173614_AddEngravingTextToCartItemAndOrderItem') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251230173614_AddEngravingTextToCartItemAndOrderItem', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230182927_AddEngravingFieldsToProduct') THEN
    ALTER TABLE "Products" ADD "DefaultEngravingText" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230182927_AddEngravingFieldsToProduct') THEN
    ALTER TABLE "Products" ADD "HasEngraving" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251230182927_AddEngravingFieldsToProduct') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251230182927_AddEngravingFieldsToProduct', '8.0.0');
    END IF;
END $EF$;
COMMIT;

